# Generated by Django 4.2.16 on 2024-09-20 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementPortal.rentalorder')),
            ],
        ),
    ]
