# Generated by Django 4.2.16 on 2024-09-23 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0002_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='dropoff_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='pickup_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
