# Generated by Django 4.2.16 on 2024-09-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0003_rentalorder_dropoff_time_rentalorder_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='location',
            field=models.CharField(default='123 your place rd.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='dropoff_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
