# Generated by Django 4.2.16 on 2024-09-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0004_rentalorder_location_alter_rentalorder_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='cleaned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='extrasRented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='extrasReturned',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='fuel_return_level',
            field=models.CharField(default='F', max_length=3),
            preserve_default=False,
        ),
    ]
