# Generated by Django 4.2.16 on 2024-09-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0005_inspection_cleaned_inspection_extrasrented_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='extrasRented',
            new_name='extras_rented',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='extrasReturned',
            new_name='extras_returned',
        ),
    ]
