# Generated by Django 4.2.16 on 2024-10-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0006_rename_extrasrented_inspection_extras_rented_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('lift_capacity', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),

        migrations.RunSQL(
            """
            INSERT INTO managementPortal_equipmenttype (name, category, manufacturer, lift_capacity) VALUES
            ('8K', 'Forklift', '', '10,000 lbs'),
            ('9K', 'Forklift', '', '5,000 lbs');
            """,
        ),
    ]
