# Generated by Django 4.2.16 on 2024-10-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0007_equipmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='managementPortal.equipmenttype'),
            preserve_default=False,
        ),

         # Update existing rows with a default equipment_type_id
        migrations.RunSQL(
            """
            UPDATE managementPortal_equipment
            SET equipment_type_id = 1
            WHERE equipment_type_id IS NULL;
            """,
        ),
    ]
