# Generated by Django 4.2.16 on 2024-10-02 15:39

from django.db import migrations, models
import django.db.models.deletion

# Step 4: This function will set default equipment_type_id for existing Equipment entries
def update_equipment_type(apps, schema_editor):
    Equipment = apps.get_model('managementPortal', 'Equipment')
    EquipmentType = apps.get_model('managementPortal', 'EquipmentType')

    # Set the default equipment type
    default_type = 1

    # Assign the default equipment_type_id to all Equipment records
    Equipment.objects.all().update(equipment_type=default_type)

class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0007_equipmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_type_id',
            field=models.IntegerField(null=True),  # Initially nullable to avoid FK checks
            preserve_default=False,
        ),

        migrations.RunPython(update_equipment_type),    # Step 4: Update existing Equipment entries

        migrations.AlterField(
            model_name='equipment',
            name='equipment_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementPortal.equipmenttype'),
        ),
    ]
