# Generated by Django 4.2.16 on 2024-10-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0008_equipment_equipment_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equipment_type_id',
            new_name='equipment_type',
        ),
    ]
