# Generated by Django 4.2.16 on 2024-10-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0009_rename_equipment_type_id_equipment_equipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='lift_capacity',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='available_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='specs',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
