# Generated by Django 4.2.16 on 2024-10-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0010_remove_equipmenttype_lift_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='specs',
        ),
    ]
