# Generated by Django 4.2.16 on 2024-10-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0011_remove_equipment_available_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='cost_per_day',
            new_name='daily_rate',
        ),
        migrations.AddField(
            model_name='equipment',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weekly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
