# Generated by Django 4.2.16 on 2024-10-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0012_rename_cost_per_day_equipment_daily_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='fuel_return_level',
            field=models.CharField(max_length=5),
        ),
    ]
