# Generated by Django 4.2.16 on 2024-10-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0013_alter_inspection_fuel_return_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='num_times_extended',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RentalExtensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_end_date', models.DateField()),
                ('days_extended', models.IntegerField()),
                ('new_end_date', models.DateField()),
                ('timestamp', models.DateTimeField()),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementPortal.rentalorder')),
            ],
        ),
    ]
