# Generated by Django 4.2.16 on 2024-10-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0014_rentalorder_num_times_extended_rentalextensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='num_times_extended',
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
