# Generated by Django 4.2.16 on 2024-10-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0015_remove_rentalorder_num_times_extended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='monthly_rate',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='weekly_rate',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='weekly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
