# Generated by Django 4.2.16 on 2024-10-10 16:21

from django.db import migrations

# Step 3: This function will insert the default EquipmentType into the table
def populate_equipment_type(apps, schema_editor):
    # We use the historical model so the migration can work without issues
    EquipmentType = apps.get_model('managementPortal', 'EquipmentType')
    
    # Check if the EquipmentType table is empty, then add a default entry
    if not EquipmentType.objects.filter(id=1).exists():
        EquipmentType.objects.create(id=1, name='Default Type', category='Default Category')

# Step 4: This function will set default equipment_type_id for existing Equipment entries
def update_equipment_type(apps, schema_editor):
    Equipment = apps.get_model('managementPortal', 'Equipment')
    EquipmentType = apps.get_model('managementPortal', 'EquipmentType')

    # Fetch the default equipment type
    default_type = EquipmentType.objects.get(id=1)

    # Assign the default equipment_type_id to all Equipment records
    Equipment.objects.all().update(equipment_type=default_type)

class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0015_remove_rentalorder_num_times_extended_and_more'),
    ]

    operations = [
    ]
