# Generated by Django 4.2.16 on 2024-10-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0016_remove_equipment_daily_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='imgURL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='imgURL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
