# Generated by Django 4.2.16 on 2024-10-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0017_equipment_imgurl_equipmenttype_imgurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalorder',
            old_name='payment_status',
            new_name='paid',
        ),
    ]
