# Generated by Django 4.2.16 on 2024-10-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0018_rename_payment_status_rentalorder_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
