# Generated by Django 4.2.16 on 2024-10-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0019_rentalorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='rental_returned',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
