# Generated by Django 4.2.16 on 2024-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0021_equipment_out_for_repairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='dropoff_time',
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='rental_approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
