# Generated by Django 4.2.16 on 2024-11-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0022_remove_rentalorder_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalextensions',
            name='extension_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
