# Generated by Django 4.2.16 on 2024-11-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0023_rentalextensions_extension_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalextensions',
            name='extension_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
