# Generated by Django 4.2.16 on 2024-11-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0024_rentalextensions_extension_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalextensions',
            old_name='extension_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='rentalextensions',
            old_name='extension_paid',
            new_name='paid',
        ),
    ]
