# Generated by Django 4.2.16 on 2024-11-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0025_rename_extension_cost_rentalextensions_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementAlertNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
