# Generated by Django 4.2.16 on 2024-12-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0026_managementalertnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementPortal.rentalorder')),
            ],
        ),
    ]
