# Generated by Django 4.2.16 on 2024-12-11 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0027_transportrate_transportorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementalertnumber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='managementalertnumber',
            name='employee_notification_preference',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalextensions',
            name='rental_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='managementPortal.rentalorder'),
        ),
    ]
