# Generated by Django 4.2.16 on 2025-02-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0029_equipmenttype_dr_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='dr_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Daily Rate Discount Amount (in dollars)'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='mr_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Rate Discount Amount (in dollars)'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='wr_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weekly Rate Discount Amount (in dollars)'),
        ),
    ]
