# Generated by Django 4.2.16 on 2025-02-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0030_alter_equipmenttype_dr_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='dr_discount_amount',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='mr_discount_amount',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='wr_discount_amount',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='discounted_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Daily Rate Discounted Price (leave blank for no discount)'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='discounted_monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Rate Discounted Price (leave blank for no discount)'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='discounted_weekly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weekly Rate Discounted Price (leave blank for no discount)'),
        ),
    ]
