# Generated by Django 4.2.16 on 2025-02-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0031_remove_equipmenttype_dr_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='discounted_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discounted Daily Rate (leave blank for no discount)'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='discounted_monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discounted Monthly Rate (leave blank for no discount)'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='discounted_weekly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discounted Weekly Rate (leave blank for no discount)'),
        ),
    ]
