# Generated by Django 4.2.16 on 2025-03-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0033_companysettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanySettings',
            new_name='CompanySetting',
        ),
    ]
