# Generated by Django 4.2.16 on 2025-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0034_rename_companysettings_companysetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysetting',
            name='company_phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
