# Generated by Django 4.2.16 on 2025-03-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0035_alter_companysetting_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysetting',
            name='company_phone',
            field=models.CharField(default='8011231234', max_length=15),
        ),
    ]
