# Generated by Django 4.2.16 on 2025-03-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0036_alter_companysetting_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalextensions',
            name='payment_receipt_url',
            field=models.CharField(default='noURL', max_length=100),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='payment_receipt_url',
            field=models.CharField(default='noURL', max_length=100),
        ),
    ]
