# Generated by Django 4.2.16 on 2025-03-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0037_rentalextensions_payment_receipt_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorder',
            name='rental_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementPortal.rentalorder'),
        ),
    ]
