# Generated by Django 4.2.16 on 2025-03-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0038_alter_transportorder_rental_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='owner_name',
            field=models.CharField(default='Demo Owner Signature', max_length=100),
        ),
    ]
