# Generated by Django 4.2.16 on 2025-03-26 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0039_companysetting_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signed', models.DateField()),
                ('customer_signature', models.CharField(max_length=50)),
                ('business_signature', models.CharField(max_length=50)),
                ('agreement_box_checked', models.BooleanField(default=True)),
                ('associated_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementPortal.rentalorder')),
            ],
        ),
    ]
