# Generated by Django 4.2.16 on 2025-07-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0040_signedcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='security_deposits_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transportorder',
            name='rental_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_order', to='managementPortal.rentalorder'),
        ),
    ]
