# Generated by Django 4.2.16 on 2025-07-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0041_companysetting_security_deposits_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='default_security_deposit',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
    ]
