# Generated by Django 4.2.16 on 2025-07-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0042_companysetting_default_security_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
