# Generated by Django 4.2.16 on 2025-08-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0043_rentalorder_security_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='square_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
