# Generated by Django 4.2.16 on 2025-08-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementPortal', '0045_rentalextensions_idempotency_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalextensions',
            name='square_payment_id',
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='square_payment_id',
        ),
    ]
