# Generated by Django 4.2.16 on 2024-10-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerPortal', '0003_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
    ]
