# Generated by Django 4.2.16 on 2024-10-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerPortal', '0004_remove_customer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
