# Generated by Django 4.2.16 on 2024-10-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerPortal', '0005_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
