# Generated by Django 4.2.16 on 2024-11-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerPortal', '0006_customer_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custNotificationPreference',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
