# Generated by Django 4.2.16 on 2024-11-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerPortal', '0007_customer_custnotificationpreference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='custNotificationPreference',
            new_name='cust_notification_preference',
        ),
    ]
