# Generated by Django 4.2.16 on 2025-03-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerPortal', '0008_rename_custnotificationpreference_customer_cust_notification_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='DemoRentals', max_length=100)),
                ('company_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
