# Generated by Django 4.2.16 on 2025-03-10 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerPortal', '0009_companysettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySettings',
        ),
    ]
